CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250401234650_BookAndGenreMigration') THEN
    CREATE TABLE "Genres" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "CreationDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250401234650_BookAndGenreMigration') THEN
    CREATE TABLE "Books" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(100) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "ImageUrl" character varying(1000) NOT NULL,
        "Publisher" character varying(100) NOT NULL,
        "PublishDate" timestamp with time zone NOT NULL,
        "Isbn" character varying(13) NOT NULL,
        "GenreId" integer,
        CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Books_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genres" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250401234650_BookAndGenreMigration') THEN
    CREATE INDEX "IX_Books_GenreId" ON "Books" ("GenreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250401234650_BookAndGenreMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250401234650_BookAndGenreMigration', '8.0.14');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405163639_BookStatus') THEN
    ALTER TABLE "Books" ADD "Status" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250405163639_BookStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250405163639_BookStatus', '8.0.14');
    END IF;
END $EF$;
COMMIT;

