CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Genres" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "ImageUrl" character varying(1000) NOT NULL,
    "Publisher" character varying(100) NOT NULL,
    "PublishDate" timestamp with time zone NOT NULL,
    "Isbn" character varying(13) NOT NULL,
    "GenreId" integer,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genres" ("Id")
);

CREATE INDEX "IX_Books_GenreId" ON "Books" ("GenreId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250401234650_BookAndGenreMigration', '8.0.14');

COMMIT;

